services:
  backend:
    build:
      context: .  # Root directory for backend Dockerfile
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "8080:8080"
    volumes:
      - ./node:/app
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword  # Provide DB password
      - DB_NAME=mydatabase  # Provide DB name

  frontend:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set root password here
      MYSQL_DATABASE: mydatabase  # Set default database name
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
