services:
  laravel-docker:
    container_name: laravel_docker_tuts
    build: .
    volumes:
      - ./dockerize_lara_app:/var/www/html
    ports:
      - 8090:80

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1
